spring.application.name=pos-coffee-be
spring.datasource.url=jdbc:sqlserver://ip.ean.vn:1433;databaseName=poscoffee;encrypt=false

spring.datasource.username=poscoffeeuser
spring.datasource.password=123123Aa

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
spring.jpa.properties.hibernate.hbm2ddl.auto=update
spring.jpa.properties.hibernate.show_sql=true

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

jwt.secret=pos-coffee-fcc-jwt-secret-an-quy-yo-mnhat-hnhat-phat
jwt.expiration-ms=86400000
